### PR TITLE
fallbackToDestructiveMigration is added

### PR DESCRIPTION
**Pull request by Faiizii**
Hey there! 
I created a pull request to allow the fallbackToDestructiveMigration. Please check and review the request if it full fill the standards, and let me know if there's any thing missing or required to explain.

### CODE REVIEW

**Comment by vitusortner** [comment]
The new files and changes in the example directory add a lot of noise to the PR. Do we need them or could we just get rid of them? @Faiizii

**Comment by Faiizii** [comment]
@vitusortner  The example (directory) was created with android support lib but flutter latest version using androidx lib for android. So, to support latest versions for both android and iOS, I deleted the both android and iOS folder and executed the `flutter create .` command, and the flutter created the required files. 
If you don't want them to be the part of the repo, we can go with old version of example directory

**Comment by wamaeb** [comment]
Whatever happened to this?

**Comment by Faiizii** [comment]
> Whatever happened to this?

the owner did not accept the merge sadly.

**Comment by hm-tamim** [comment]
Any update on this?

**Comment by hm-tamim** [comment]
any update on this PR?

**Comment by dkaera** [comment]
Hello @hm-tamim 
currently not
plan to update and check it out next

**Comment by dkaera** [comment]
I think fallbackToDestructiveMigration should be managed by a config option during database initialization (not from generated code). It makes it easy to manage, just like it works in the Room Persistence library.
The current implementation is quite outdated and contains a lot of noise unrelated to the implementation of the feature.
If you need this functionality please use this [fork](https://github.com/pinchbv/floor/pull/572#issuecomment-960538567)

**Pull request closed without merging**
