### PR TITLE
feat: Web support

### PR DESCRIPTION
**Pull request by mirland**
Right now [sqflite_common_ffi_web](https://pub.dev/packages/sqflite_common_ffi_web) is in an experimental state, but if we add the factory, we can support the web optionally.

What do you think?

Currently, floor doesn't support web and we cannot update the factory creator, so if we want to support web we have to change the generated code (or duplicate code), and it's not a good idea.
This pr adds the web factory

### CODE REVIEW

**Comment by dkaera** [comment]
wow, looks good, did you test it out?

**Comment by mirland** [comment]
Yes doing these changes manually I could make my application work. I tested in [this branch](https://github.com/xmartlabs/fluttips/tree/feature/web-support), but I did floor changes just locally

**Comment by dkaera** [comment]
> Yes doing these changes manually I could make my application work. I tested in [this branch](https://github.com/xmartlabs/fluttips/tree/feature/web-support), but I did floor changes just locally

awesome, I'll prepare the project update PR, because the current one contains a lot of changes in the `.lock` file, which doesn't related to the main change.

**Review by dkaera — DISMISSED** [review]

**Comment by dkaera** [comment]
Hey @mirland
`ubuntu` job broke, I fixed it in my PR
let's merge your changes after mine

**Review by ThomasMiddel — APPROVED** [review]

**Comment by mirland** [comment]
Hi @dkaera, do you have any feedback for my PR? I don't know if I can do something to merge it

**Comment by mirland** [comment]
> the coverage check blocks this PR, so you need to add the corresponding test for the newly added condition first

Hi @dkaera , can you suggest to me how can I do that, in this case, there's no test to do, I mean, if we want to do that we should like mock the platform and check the factory. I checked your tests and that method seems to be not tested and there's not something similar

**Comment by mirland** [comment]
> the coverage check blocks this PR, so you need to add the corresponding test for the newly added condition first

Hi @dkaera , can you suggest to me how can I do that, in this case, there's no test to do, I mean, if we want to do that we should like mock the platform and check the factory. I checked your tests and that method seems to be not tested and there's not something similar

**Comment by mirland** [comment]
@dkaera can you suggest to me what kind of test should I include?

**Comment by dkaera** [comment]
> @dkaera can you suggest to me what kind of test should I include?

ah, I'm sorry, I can't help you now, because of the heavy workload.

**Comment by mirland** [comment]
Ok, np, no rush. Then when you have time, please check it because I changed only 3 lines and I think I cannot do a test for that.

image

Thanks!

**Comment by dkaera** [comment]
> Ok, np, no rush. Then when you have time, please check it because I changed only 3 lines and I think I cannot do a test for that.
> 
> image
> 
> Thanks!

I think we can mock `Platform` value and verify what the instance was factory created.

**Comment by stefanosiano** [comment]
any news on this? 
No rush, i'd just like to try floor instead of sqflite in my project, which runs on desktop and web

**Comment by hendrikvdkaaden** [comment]
I really appreciate this feature and would like to continue working with it. However, I encountered an issue when launching the example project on the web using your branch. The error message displayed is:

-----------------------------------------------------------------------------------------
An error occurred while initializing the web worker.
This is likely due to a failure to find the worker javascript file at sqflite_sw.js

Please check the documentation at https://github.com/tekartik/sqflite/tree/master/packages_web/sqflite_common_ffi_web#setup-binaries to setup the needed binaries.

Error: SqfliteFfiWebException()
-----------------------------------------------------------------------------------------

Do you have any insights into the cause of this problem?

**Comment by stephanmantel** [comment]
> > Ok, np, no rush. Then when you have time, please check it because I changed only 3 lines and I think I cannot do a test for that.
> > image
> > Thanks!
> 
> I think we can mock `Platform` value and verify what the instance was factory created.

Is it possible to mock Platform and kIsWeb? I found no support for static mocking using Mockito.

We could also resort to a wrapper object, but I feel like that misses the point a bit, as the real logic you'd want to test is mocked away. What do you guys think, is is necessary to test this?

**Comment by dkaera** [comment]
Hey guys
With pr #815 issues should sorted
Lets push it to development brunch then we can merge @mirland changes to support web 
I tested it locally - everything works fine 💪💪💪

**Comment by hendrikvdkaaden** [comment]
Is this PR still relevant, since it's merged to #819?

**Comment by dkaera** [comment]
@hendrikvdkaaden yes we can close this PR

**Comment by dkaera** [comment]
the changes were picked up and integrated separately

**Pull request closed without merging**
